"""Render the dbt DAG from target/manifest.json as a Mermaid diagram (GitHub renders it inline)."""
from __future__ import annotations

import json

from pipeline_common.config import ROOT

LAYER_ORDER = ["source", "staging", "intermediate", "marts"]


def main() -> None:
    manifest = json.loads((ROOT / "dbt_project" / "target" / "manifest.json").read_text())
    nodes = {**manifest["nodes"], **manifest["sources"]}
    edges, layers = [], {layer: [] for layer in LAYER_ORDER}

    def label(uid: str) -> str:
        n = nodes[uid]
        return f"raw.{n['name']}" if n["resource_type"] == "source" else n["name"]

    layers["source"] += list(manifest["sources"])
    for uid, node in manifest["nodes"].items():
        if node["resource_type"] != "model":
            continue
        layers[node["fqn"][1]].append(uid)
        edges += [(parent, uid) for parent in node["depends_on"]["nodes"] if parent in nodes]

    lines = ["```mermaid", "flowchart LR"]
    for layer in LAYER_ORDER:
        lines.append(f'  subgraph {layer}["{layer}"]')
        lines += [f'    {nodes[u]["name"]}["{label(u)}"]' for u in sorted(layers[layer])]
        lines.append("  end")
    lines += [f"  {nodes[a]['name']} --> {nodes[b]['name']}" for a, b in sorted(edges)]
    lines.append("```")
    out = ROOT / "docs" / "lineage.md"
    out.write_text("# dbt lineage\n\nGenerated by `make lineage` from `target/manifest.json`.\n\n"
                   + "\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
